import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../providers/auth_providers.dart';
import '../../widgets/section_card.dart';

final reportsProvider =
    StreamProvider<List<QueryDocumentSnapshot<Map<String, dynamic>>>>((ref) {
  return ref
      .watch(adminFirestoreServiceProvider)
      .watchCollection('reports', orderBy: 'createdAt', descending: true);
});

class ReportsPage extends ConsumerWidget {
  const ReportsPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final reportsAsync = ref.watch(reportsProvider);
    final isCompact = MediaQuery.of(context).size.width < 860;
    final formatter = DateFormat('yyyy-MM-dd');

    return reportsAsync.when(
      data: (docs) {
        if (docs.isEmpty) {
          return const Center(child: Text('No reports found.'));
        }
        if (isCompact) {
          return ListView.separated(
            itemCount: docs.length,
            separatorBuilder: (_, __) => const SizedBox(height: 12),
            itemBuilder: (context, index) {
              final data = docs[index].data();
              return SectionCard(
                title: data['type']?.toString() ?? 'Report',
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('From: ${_formatDate(data['dateFrom'], formatter)}'),
                    Text('To: ${_formatDate(data['dateTo'], formatter)}'),
                    Text('Generated by: ${data['generatedBy'] ?? '--'}'),
                    Text('File URL: ${data['fileUrl'] ?? '--'}'),
                  ],
                ),
              );
            },
          );
        }

        return SingleChildScrollView(
          child: DataTable(
            columns: const [
              DataColumn(label: Text('Type')),
              DataColumn(label: Text('From')),
              DataColumn(label: Text('To')),
              DataColumn(label: Text('Generated by')),
              DataColumn(label: Text('File URL')),
            ],
            rows: [
              for (final doc in docs)
                DataRow(cells: [
                  DataCell(Text(doc.data()['type']?.toString() ?? '--')),
                  DataCell(Text(_formatDate(doc.data()['dateFrom'], formatter))),
                  DataCell(Text(_formatDate(doc.data()['dateTo'], formatter))),
                  DataCell(Text(doc.data()['generatedBy']?.toString() ?? '--')),
                  DataCell(
                    SizedBox(
                      width: 220,
                      child: SelectableText(
                        doc.data()['fileUrl']?.toString() ?? '--',
                      ),
                    ),
                  ),
                ]),
            ],
          ),
        );
      },
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, _) => Center(child: Text('Error: $error')),
    );
  }
}

String _formatDate(dynamic value, DateFormat formatter) {
  if (value is Timestamp) {
    return formatter.format(value.toDate());
  }
  return value?.toString() ?? '--';
}
